from typing import Protocol, TypeVar

K_contra = TypeVar("K_contra", contravariant=True)
K = TypeVar("K")
V = TypeVar("V")


class Storage(Protocol[K_contra, V]):
    def set(self, key: K_contra, value: V) -> None: ...
    def get(self, key: K_contra) -> V | None: ...
    def exists(self, key: K_contra) -> bool: ...
    def remove(self, key: K_contra) -> None: ...
    def clear(self) -> None: ...


class Policy(Protocol[K]):
    @property
    def has_keys(self) -> bool: ...
    def register_access(self, key: K) -> None: ...
    def get_key_to_evict(self) -> K | None: ...
    def remove_key(self, key: K) -> None: ...
    def clear(self) -> None: ...


class Cache(Protocol[K_contra, V]):
    def __init__(
        self,
        storage: Storage[K_contra, V],
        policy: Policy[K_contra],
    ) -> None: ...
    def set(self, key: K_contra, value: V) -> None: ...
    def get(self, key: K_contra) -> V | None: ...
    def exists(self, key: K_contra) -> bool: ...
    def remove(self, key: K_contra) -> None: ...
    def clear(self) -> None: ...


class HasCache(Protocol[K, V]):
    cache: Cache[K, V]
